### ISSUE TITLE
Not able to start play test

### ISSUE THREAD

**Issue by SeanWangDev** [quxios/QMV-Master-Demo#7]
Hi Quxios,

Thanks for the demo, though I cannot start the play test, but starting QMV-ABS-demo was successful.

What I saw was a total black window, and F8 has no response. And in RPG Maker, the map named QMap is empty with only an event returning to QIslands map.

Did I miss something?

Sean

**Comment by quxios** [comment]
I just redownloaded and tested  and it ran fine for me. Did you follow the steps listed in the README.md? And is you RMMV updated? My plugins are made to work with the lastest versions, so if you have an outdated version it may not work.
As for the QMap, in the editor it should be blank with only an event because QMap uses an [external editor](https://github.com/quxios/QMapEditor) to make the maps. But ingame the map is still blank which is due to an outdated QMap.json, which I'll update in a minute, so thanks for reporting that!

**Comment by SeanWangDev** [comment]
I think I did follow the steps, clone and copy the files to a new project. Though I still cannot get it run. The version is v1.5.1, from Steam, on OSX El Capitan.
What will be the start screen for a fine run play test? If I can find any log files, I can send it to you.

Sean
